### ISSUE TITLE
wrong information shown on "boleto" checkout

### ISSUE THREAD

**Issue by bolds07** [mercadopago/px-android#1464]
The api informs the incorrect barcode to customers who choose the payment with the boleto bancario option in brazil....

You should follow the steps to reproduce the error:

1-in backeend I create a "preference" with any product and any customer

2-using the mobile checkout on android I started the checkout process with a preference created

3-the customer chose the BOLETO BANCARIO option

4-the client informs his identification data

5- client confirm purchase

MP checkout shows the confirmation and gives the user 2 options: 

A) Print the boleto bancario to pay

B) copy the barcode to pay on internet banking on the cell phone

https://ibb.co/GtjvZhm

THE PROBLEM: the bar code reported in option B is ALWAYS an invalid code

As it is possible to see in the photo of the above link the bar code informed to the client is

2379 1774 1000 0002 9993 3802 6037 3110 0745 0063 33330

ENTERING by clicking VER BOLETO the customer is taken to a ticket page

https://www.mercadopago.com/mlb/payments/ticket/helper?payment_id=4364519313&payment_method_reference_id=3731100745&caller_id=147602979&hash=4ec648de-cb26-4db3-897c-57b78b703b5c

on this page the actual barcode is:

23793 38029 60373 110075 450063 33301 1 77410000002999

IT IS POSSIBLE TO SEE EASILY THAT THE TWO NUMBER ARE TOTALLY DIFFERENT

Customers who try to copy/paste the informed barcode during checkout gets an error in internet banking receive and come to me to complain....

The preference I used in the example was: "217335314-a346534a-b27a-434b-b4fd-f919698dd336" but this happens to anyone I test

fix this problem or at least stop showing the option to copy this bar code since it is always wrong

**Comment by zehemz** [comment]
@marcospicco Can you see this?

**Comment by zehemz** [comment]
@bolds07 do you want to send me an email to lucas.bais@mercadolibre.com ? I think it will be nice to have your contact info.

**Comment by zehemz** [comment]
@bolds07 we will place a fix for this from backend after christmas.

**Comment by zehemz** [comment]
@bolds07 this issue should be fixed, please try again! Thank you for the report.

**Comment by leandrodimitrio** [comment]
Hey guys, issue is still exactly the same. As it appears, many of the digits are correct, but in the wrong position.

barcode->content: 23792824700000010003380260657338279900633330
actual barcode in PDF: 23793.38029 60657.338277 99006.333308 2 82470000001000
